---
title: "Ricci static"
output: html_document
---

```{r, echo=FALSE}
library(ggplot2)
library(dplyr)
library(magrittr)
library(apTreeshape)

source("process.R")

make_density <- function(d) {
  ggplot(d, aes(kappa, color=t1_nwk)) +
    facet_wrap(~ dist, ncol=2, scales="free") + theme(aspect.ratio=0.62) +
    geom_density()
}

make_heat <- function(d) {
  d[,c("dist", "t1_colless", "t2_colless", "kappa")] %>%
  group_by(dist, t1_colless, t2_colless) %>%
  summarise(mean = mean(kappa), median = median(kappa)) %>%
  ggplot(aes(t1_colless, t2_colless)) +
    facet_wrap(~ dist, ncol=2, scales="free") + theme(aspect.ratio=0.62) +
    geom_tile(aes(fill=mean))
}

analyze <- function(path) {
  d <- get_results(path)
  print(make_density(d))
  print(make_heat(d))
}
```

## 5 leaves
```{r, echo=FALSE, dpi=120}
analyze("../../results-rspr/ricci5.mat")
```

## 6 leaves
```{r, echo=FALSE, dpi=170}
analyze("../../results-rspr/ricci6.mat")
```

## 7 leaves
```{r, echo=FALSE, dpi=200}
analyze("../../results-rspr/ricci7.mat")
```
